name: Update GitHub Project from Excel（Tmp）

on:
  workflow_dispatch:
    inputs:
      excel_file_path:
        description: 'Path to Excel file'
        required: true
        default: 'GitHubExport.xlsx'

jobs:
  update_project:
    runs-on: windows-latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # プロジェクトに使用している.NETのバージョン           
    
    - name: Run executable
      run: |
        $githubToken = "${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}"
        $excelFilePath = "${{ github.workspace }}/${{ github.event.inputs.excel_file_path }}"
        $projectName = 'KanbanTest'
        $owner = "${{ github.repository_owner }}"
        $repo = "${{ github.event.repository.name }}"

        $exePath = "${{ github.workspace }}\GitHubExport\GitHubExport\bin\Release\net8.0\GitHubExport.exe"

        # 実行ファイルが存在するか確認
        if (-Not (Test-Path $exePath)) {
          Write-Error "実行ファイルが見つかりません: $exePath"
          exit 1
        }

        # 実行するExcelファイルが存在するか確認
        if (-Not (Test-Path $excelFilePath)) {
          Write-Error "Excelファイルが見つかりません: $excelFilePath"
          exit 1
        }

        try {
          & $exePath $githubToken $excelFilePath $projectName $owner $repo
          Write-Host "実行が成功しました。"
        } catch {
          Write-Error "実行中にエラーが発生しました: $_"
          exit 1  # 実行が失敗した場合は、ワークフローを失敗させる
        }
      shell: pwsh
