name: Update GitHub Project from Excel

on:
  workflow_dispatch:
    inputs:
      excel_file_path:
        description: 'Path to Excel file'
        required: true
        default: 'GitHubExport2.xlsx'

jobs:
  update_project:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!!"