name: Update GitHub Project from Excel

on:
  workflow_dispatch:
    inputs:
      excel_file_path:
        description: 'Path to Excel file'
        required: true
        default: 'GitHubExport2.xlsx'

jobs:
  update_project:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # または、プロジェクトで使用している.NETのバージョン

    - name: Run executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_NAME: "KanbanTest"
      run: |
        $githubToken = "${{ secrets.GITHUB_TOKEN }}"
        $excelFilePath = "${{ github.workspace }}/${{ github.event.inputs.excel_file_path }}"
        $projectName = "KanbanTest"
        $owner = "${{ github.repository_owner }}"
        $repo = "${{ github.event.repository.name }}"

        $exePath = "${{ github.workspace }}\GitHubExport\GitHubExport\bin\Release\net8.0\GitHubExport.exe"

        & $exePath $githubToken $excelFilePath $projectName $owner $repo
      shell: pwsh
