name: Update GitHub Project from Excel

on:
  workflow_dispatch:
    inputs:
      excel_file_path:
        description: 'Path to Excel file'
        required: true
        default: 'GitHubExport2.xlsx'

jobs:
  update_project:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # または、プロジェクトで使用している.NETのバージョン

    - name: Run executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
      run: |
        $githubToken = "${{ secrets.GITHUB_TOKEN }}"
        Write-Host "githubToken: $githubToken"
        $excelFilePath = "${{ github.workspace }}/${{ github.event.inputs.excel_file_path }}"
        Write-Host "excelFilePath: $excelFilePath"
        $projectName = "${{ env.PROJECT_NAME }}"
        Write-Host "projectName: $projectName"
        $owner = "${{ github.repository_owner }}"
        Write-Host "owner: $owner"
        $repo = "${{ github.event.repository.name }}"
        Write-Host "repo: $repo"
        $exePath = "GitHubExport\GitHubExport\bin\Release\net8.0\GitHubExport.exe"
        Write-Host "exePath: $exePath"
        & $exePath $githubToken $excelFilePath $projectName $owner $repo
      shell: pwsh
